api/urls.py
from django.urls import path
from .views import (
    ListPersonsAPIView,
    RetrieveUpdateDestroyPersonsAPIView,
    CreatePersonsAPIView
)


app_name = 'api'
urlpatterns = [
    path('list/', ListPersonsAPIView.as_view(), name='list'),
    path('<int:id>/',  RetrieveUpdateDestroyPersonsAPIView.as_view(), name='retrieve_update_delete'),
    path("", CreatePersonsAPIView.as_view(), name='create')
]

hng_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', TemplateView.as_view(template_name = 'api_docs.html'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

api/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Persons(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(null= True, blank=True)
    nationality = models.CharField(max_length=200)
    state_of_origin = models.CharField(max_length=200)
    occupation = models.CharField(max_length=200)

    
    # def get_absolute_url(self, *args, **kwargs):
    #     return reverse('')

api/views.py
from django.shortcuts import render
from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView,
    UpdateAPIView,
    CreateAPIView,
    DestroyAPIView,
    RetrieveUpdateAPIView,
    RetrieveUpdateDestroyAPIView
)
from .models import Persons
from rest_framework import permissions, authentication
from .permissions import UserPerm
from .serializers import PersonsSerializers


# Create your views here.
class ListPersonsAPIView(ListAPIView):
    queryset = Persons.objects.all()
    serializer_class = PersonsSerializers
    # permission_classes = [permissions.IsAuthenticatedOrReadOnly | UserPerm]
    # authentication_classes = [authentication.SessionAuthentication]


# class RetrievePersonsAPIView(RetrieveAPIView):
#     queryset = Persons.objects.all()
#     serializer_class = PersonsSerializers
#     lookup_field = 'id'
#     permission_classes = [permissions.IsAuthenticatedOrReadOnly | UserPerm]
#     authentication_classes = [authentication.SessionAuthentication]


class RetrieveUpdateDestroyPersonsAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Persons.objects.all()
    serializer_class = PersonsSerializers
    lookup_field = 'id'
    # permission_classes = [permissions.IsAuthenticatedOrReadOnly | UserPerm]
    # authentication_classes = [authentication.SessionAuthentication]
    
    def update(self, request, *args, **kwargs):
        return super().update(request, *args, **kwargs)
    
class CreatePersonsAPIView(CreateAPIView):
    queryset = Persons.objects.all()
    serializer_class = PersonsSerializers
    # permission_classes = [permissions.IsAuthenticatedOrReadOnly | UserPerm]
    # authentication_classes = [authentication.SessionAuthentication]

# class DestroyPersonsAPIView(DestroyAPIView):
#     queryset = Persons.objects.all()
#     serializer_class = PersonsSerializers
#     permission_classes = [permissions.IsAuthenticatedOrReadOnly | UserPerm]
#     authentication_classes = [authentication.SessionAuthentication]

api/templates/api_docs.html
{% extends 'base.html' %}
{% load static %}

{% block mycss %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/api_docs.css' %}">
    <link rel="stylesheet" href="{% static 'css/create_api_key.css' %}">
    
{% endblock %}
{% block content %}
    {% include 'navbar.html' %}
    <div class="">
        <div class="row topics-row">
            {% include 'docsNavbar.html' %}
            <div class="col-lg-6 text-con">
                <section class="text-section" id="introduction">
                    <div class="godocs-title">
                        <p><i class="fa-sharp fa-solid fa-file"></i> <span class="brand-name">HngDocs</span> API Documentation</p>
                    </div>
                    <div class="con-text-section">
                        <h4>Introduction</h4>
                        <p>
                            This is an efficient API tool that provides a user friendly way of creating individuals
                        </p>
                        <h6>Reasons why you may want to use this API</h6>
                        <ul>
                            <li>Extensive documentation and great community support.</li>
                            <li>Easy to use and customizable all the way down.</li>
    

                        </ul>
                        <hr>
                        <section id="getting-started">
                            <div class="con-text-section">
                                <h4>Get Started</h4>
                                <img src="{% static 'img/hng_project.png' %}" alt="uml_diagram" class="uml_diagram">
                            </div>
                        </section>
                        <hr>
                        <section id="create-account">
                            <div class="con-text-section">
                                <h4>How to create users using the API Endpoint</h4>
                                Make a Post request using the endpoint:
                                <div class="request">
                                    <p class="authorized-request create-endpoint">
                                        https://{{request.META.HTTP_HOST}}{% url 'api:create' %}
                                    </p>
                                    <i class="fa-sharp fa-solid fa-clipboard copy copy-2"></i>        
                                </div>

                                <p>The underlisted parameters are needed when creating a user:</p>
                                <ul>
                                    <li>The User's Name</li>
                                    <li>The User's Email Address</li>
                                    <li>The 'User's Nationality</li>
                                    <li>The 'User's State of origin</li>
                                    <li>The 'User's Occupation</li>
                                </ul>
                                <p>
                                    The User's Name and email is made to be unique accross the board. That means that, not more than one account can be created with the same name or email.
                                    This is to ensure that, no user can have more one account.
                                    If for instance a user input the same name or email or both name and email that has been created and saved before in 
                                    the database, a status code of 400 is retured showing a bad request and returing
                                    a response showing the following:

                                    <div class="request">
                                        <p class="authorized-request bad-data">
                                            {{
                                                "name":
                                                [
                                                    "Ooops, this name already exists!!"
                                                ],
                                                <br>
                                                "email": 
                                                [
                                                    "An account has already been created with this email"
                                                ] 
                                            }}
                                        </p>
                                        <i class="fa-sharp fa-solid fa-clipboard copy copy-1"></i>        
                                    </div>


                                </p>
                                <h5>For Example: In a pythonic way, making a POST request will be something similar to this</h5>
                                <div class="request">
                                    <div class="authorized-request python-way">
                                            # pip install request 
                                            <br>
                                            import requests
                                            <br>
                                            endpoint = https://{{request.META.HTTP_HOST}}{% url 'api:create' %}
                                            <br>
                                            name = "users name" 
                                            <br>
                                            email = "user's email"
                                            <br>
                                            nationality = "users nationality"
                                            <br>
                                            state_of_origin = "users state of origin"
                                            <br>
                                            <br>
                                            occupation = "users occupation"
                                            <br>
                                            json = {'name': name, 'email': email, 'nationality': nationality, 'state_of_origin': state_of_origin, "occupation": occupation} 
                                            <br>
                                            get_response = request.post(endpoint, body = json)
                                            <br>
                                            print(get_response.status_code) # To check the status code


                                                           
                                    </div>
                                    <i class="fa-sharp fa-solid fa-clipboard copy copy-3"></i>        
                                </div>
                            </div>
                        </section>
                        <hr>
                        <section id="list-users">
                            <div class="con-text-section">
                                <h3>How to get list of all the users</h3>
                                <p>
                                    In a similar way to how we <a href="#create-account">created users</a> using the api endpoint, we can also
                                    get a list of all registered users. But this time, we are going to Make
                                    a get request to the endpoint below:
                                 </p>
                                 <div class="request">
                                    <p class="authorized-request list-endpoint">
                                        https://{{request.META.HTTP_HOST}}{% url 'api:list' %}
                                    </p>
                                    <i class="fa-sharp fa-solid fa-clipboard copy copy-4"></i>        
                                </div>
                            </div>
                        </section>
                        <hr>
                        <section id="update-users">
                            <div class="con-text-section">
                                <h3>To Update Users Credentials </h3>
                                <p>
                                    Similar to how we <a href="#create-account">created users</a>
                                    you can also update a user credentials, simply by making a 'PUT' request to
                                    the endpoint:    
                                </p>
                                <div class="request">
                                    <p class="authorized-request update-endpoint">
                                        https://{{request.META.HTTP_HOST}}{% url 'api:retrieve_update_delete' id=1 %}
                                    </p>
                                    <i class="fa-sharp fa-solid fa-clipboard copy copy-5"></i>        
                                </div>
                                Ensure you replace '{{1}}' with the user's id and add the field and also the 
                                value of the field that you want to update to the body similar to how 
                                it was done when we <a href="#create-account">created users</a> but this time 
                                selectively pick the field that you want to update. For instance; if 
                                you only want to update the name of the user, only add name as the 
                                key to the body and let the name of the user be the value. In a similar way, you can update several 
                                fieldset at the same time by inputing all the fieldset of the user that you want to update and the value 
                                to the body. 
                                <br>
                                {% comment %}
                                <p>
                                   <strong>Note:</strong> More importantly, the password fieldset can not be updated using this route. 
                                    It can only be updated if the user request for a password reset incases were the user forgets their password. A verfication email and 
                                    a link will be sent to the user via email were the user will be able to change his/her password.
                                    <a href="">Read on the various ways you can choose for your users to reset their password.</a> 

                                </p>
                                {% endcomment %}


                            </div>
                        </section>
                        <hr>
                        <section>
                            <div class="con-text-section">
                                <h3>To Retrive A Particular User</h3>
                                <p>
                                    Similar to how we performed a 'GET' request to get theb list of all users
                                    you can also get a user's identity by making a get request to the endpoint below: 

                                </p>
                                <div class="request">
                                    <p class="authorized-request retrive-endpoint">
                                        https://{{request.META.HTTP_HOST}}{% url 'api:retrieve_update_delete' id=1 %}
                                    </p>
                                    <i class="fa-sharp fa-solid fa-clipboard copy copy-6"></i>        
                                </div>
                            </div>
                            <p>Replace 1 with the user's id</p>
                        </section>
                    </div>
                </section>
                <section>
                    <div class="con-text-section">
                        <h3>To Delete A Particular User</h3>
                        <p>
                            Similar to how we performed a 'GET' request to get the list of all users
                            you can also delete a user's identity by making a DELETE request to the endpoint below: 

                        </p>
                        <div class="request">
                            <p class="authorized-request retrive-endpoint">
                                https://{{request.META.HTTP_HOST}}{% url 'api:retrieve_update_delete' id=1 %}
                            </p>
                            <i class="fa-sharp fa-solid fa-clipboard copy copy-6"></i>        
                        </div>
                    </div>
                    <p>Replace 1 with the user's id</p>
                </section>
            </div>
        </section>
            </div>
        </div>
    </div>
    <script src="{% static 'js/docs.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

{% endblock content %}

api/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    
    {% block mycss %}
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% endblock mycss %}
    {% block css %}
    {% comment %} bootstrap {% endcomment %}
    <link 
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
    crossorigin="anonymous">

    
    {% comment %} google font {% endcomment %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&family=Ubuntu:wght@300&display=swap" 
    rel="stylesheet">

    {% comment %}
        font aweosome link
    {% endcomment %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% endblock css%}
    <title>Document</title>
</head>

{% block body %}
    <body>
        {% block content %}
        {% endblock content %}

        
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
        
    </body>
{% endblock %}

</html>

api/templates/docsNavbar.html
<div class="col-lg-6 topics-listed">
    <div class="topics">
        <section>
            <div class="title-heading">
                <a href="" class="a-topics"><h5>Introduction</h5></a>
                <i class="fa-solid fa-caret-down dropdown-intro"></i>
            </div>
            
            <ul class="getting-started">
                <a href="#getting-started"><li>Getting Started</li></a>
                <li></li>
            </ul>
        </section>
        <section>
            <div class="title-heading">
                <a href="" class="a-topics"><h5>Accounts</h5></a>
                <i class="fa-solid fa-caret-down dropdown-account"></i>
            </div>
            
            
            <ul class="account-list">
                <a href="#create-account"><li>Create Users</li></a>
                <a href="#list-users"><li>List All Users</li></a>
                <a href="#update-users"><li>Update Users</li></a>
                
            </ul>
        </section>
    </div>
</div>

api/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <i class="fa-sharp fa-solid fa-file"></i>
      GoDocs
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse ms-auto" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">GitHub</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Docs
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% static 'img/hng_project.png' %}" download="uml-digram.png">UML Diagram</a></li>
            <li><a class="dropdown-item" href="#">Github Documentation</a></li>
            <li><hr class="dropdown-divider"></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light search-button" type="submit">Search</button>
        <style>
          .search-button{
            height: 30%;
            margin-top: 14px;
          }
        </style>
      </form>
    </div>
  </div>
</nav>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>